services:

  userdb:
    image: mysql
    container_name: userdb
    ports:
      - "3301:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    networks:
      - nrr

  bookingdb:
    image: mysql
    container_name: bookingdb
    ports:
      - "3302:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb
    networks:
      - nrr

  categorydb:
    image: mysql
    container_name: categorydb
    ports:
      - "3303:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: categorydb
    networks:
      - nrr

  paymentdb:
    image: mysql
    container_name: paymentdb
    ports:
      - "3304:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
    networks:
      - nrr

  salondb:
    image: mysql
    container_name: salondb
    ports:
      - "3305:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salondb
    networks:
      - nrr

  serviceofferingdb:
    image: mysql
    container_name: serviceofferingdb
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serviceofferingdb
    networks:
      - nrr

  eurekaserver:
    image: "nishan259/salon-eureka-server:v1"
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD-SHELL","curl --fail --silent eurekaserver:8070/actuator/health/readiness | grep UP || exist 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  user:
    image: "nishan259/salon-user:v1"
    ports:
      - "5001:5001"
    healthcheck:
      test: "curl --fail --silent user:5001/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: user
    depends_on:
      userdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "USER-SERVICE"
      SPRING_DATASOURCE_URL: "jdbc:mysql://userdb:3306/userdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  category:
    image: "nishan259/salon-category:v1"
    ports:
      - "5003:5003"
    healthcheck:
      test: "curl --fail --silent category:5003/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: category
    depends_on:
      categorydb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "CATEGORY-SERVICE"
      SPRING_DATASOURCE_URL: "jdbc:mysql://categorydb:3306/categorydb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  payment:
    image: "nishan259/salon-payment:v1"
    ports:
      - "5006:5006"
    healthcheck:
      test: "curl --fail --silent payment:5006/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: payment
    depends_on:
      paymentdb:
        condition: service_healthy
    environment:
      KHALTI_SECRET_KEY: your api key
      SPRING_APPLICATION_NAME: "PAYMENT-SERVICE"
      SPRING_DATASOURCE_URL: "jdbc:mysql://paymentdb:3306/paymentdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  salon:
    image: "nishan259/salon-service:v1"
    ports:
      - "5002:5002"
    healthcheck:
      test: "curl --fail --silent salon:5002/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: salon
    depends_on:
      salondb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "SALON-SERVICE"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salondb:3306/salondb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  booking:
    image: "nishan259/salon-booking:v1"
    ports:
      - "5005:5005"
    healthcheck:
      test: "curl --fail --silent booking:5005/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: booking
    depends_on:
      bookingdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "BOOKING-SERVICE"
      SPRING_DATASOURCE_URL: "jdbc:mysql://bookingdb:3306/bookingdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  service-offering:
    image: "nishan259/salon-service-offering:v1"
    ports:
      - "5004:5004"
    healthcheck:
      test: "curl --fail --silent service-offering:5004/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: service-offering
    depends_on:
      serviceofferingdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "SERVICE-OFFERING"
      SPRING_DATASOURCE_URL: "jdbc:mysql://serviceofferingdb:3306/serviceofferingdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

  gatewayserver:
    image: "nishan259/salon-gateway-server:v1"
    ports:
      - "5000:5000"
    healthcheck:
      test: "curl --fail --silent gatewayserver:5000/actuator/health/readiness | grep UP || exist 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: gatewayserver
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nrr

networks:
  nrr:
    driver: "bridge"